name: AWS Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: AWS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('./yarn.lock') }}

        # Tailwind
      - run: npx tailwindcss -i ./src/input.css -o ./src/output.css

      - run: yarn install
      - run: yarn build --mode production
        env:
          NODE_ENV: production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload files to S3
        uses: shallwefootball/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: cositas-minesweeper
          source_dir: 'dist'
          destination_dir: ''

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E29PT6YEN72GHV \
            --paths "/*"
